FROM docker.io/netboxcommunity/netbox:latest-3.3.0

COPY ./plugin_requirements.txt /opt/netbox/
RUN /usr/local/bin/uv pip install -r /opt/netbox/plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
COPY configuration/plugins.py /etc/netbox/config/plugins.py

RUN DEBUG="true" SECRET_KEY="bb8ebeff-3b91-4d66-8663-8dfcdfdcea58" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
